### ISSUE TITLE
getting error "SIGSEGV"

### ISSUE THREAD

**Issue by banty306** [srajgure/CodeChef-Solutions#1]
actually this program is giving the error "SIGABRT" 
"terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc"

even i tried to solve in c++ but getting error can you help me a bit here is my solution 
#include<bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    cin>>t;
    while(t--)
    {
        int m,n;
        cin>>n>>m;
        int arr[2][n];
        int temp[m];
        for(int i=1;i<=m;i++)
        {
            temp[i]=i;
        }
        for(int i=0;i<2;i++)
        {
            for(int j=0;j<n;j++)
            {
                cin>>arr[i][j];
            }
        }
        int p=0;
        int tem[m]={0};
        for(int k=1;k<=m;k++)
        {
        for(int i=0;i<1;i++)
        {
            for(int j=0;j<n;j++)
            {
                if(temp[k]==arr[i][j])
                {
                    tem[p]=tem[p]+arr[i+1][j];
                }
            }
        }
        p++;
        }
        sort(tem,tem+m);
        for(int i=0;i<m;i++)
        {
            if(tem[i]!=0)
            {
                cout<<tem[i]<<endl;
                break;
            }
        }
    }
    return 0;
}

**Comment by srajgure** [comment]
@banty306  which question is this?

**Comment by banty306** [comment]
first one "pinku and fruits"
